[package]
name = "eziclean"
version = "0.1.0"
authors = ["Sergey Matyukevich <geomatsi@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"
panic-semihosting = "0.5.1"
cortex-m-semihosting = "0.3.2"
panic-itm = "0.4.0"
nb = "0.1.1"
cortex-m-rtfm = "0.4.0"
