[tasks.debug-jlink]
script = [
'''
sudo tools/tmux-debug-jlink
'''
]

[tasks.debug-stlink]
script = [
'''
sudo tools/tmux-debug-stlink
'''
]

[tasks.factory-stlink]
script = [
'''
sudo openocd -f tools/openocd-stlink.cfg -c 'factory ()'
'''
]
